### ISSUE TITLE
Seems, the original repo is not supported now

### ISSUE THREAD

**Issue by lab313ru** [NovaSquirrel/Mesen-S#5]
1) Sour doesn't apply subscription at Patreon
2) Projects Mesen and Mesen-S are archived now.
3) His domain is not available.

It looks like your repo is the most supported and updated now. Will try to support you.

**Comment by NovaSquirrel** [comment]
[Sour said](https://www.reddit.com/r/emulation/comments/j58hfu/mesen_and_mesens_github_repositories_are_now/g7sti7q?utm_source=share&utm_medium=web2x&context=3) that he wanted to stop after working on emulators for years.

I still use Mesen and Mesen-S extensively for homebrew development, so I'm trying to continue it and add features that would help for that purpose. I'm intending on adding any helpful features/fixes people add to their own Mesen/Mesen-S forks too, so we can have it all in one place.

I probably won't be working on it as often as he did, but that's definitely still better than the projects just ending completely.
